repos:
  - repo: https://github.com/ztinpn/pre-commit-golang
    rev: v0.4.1
    hooks:
      - id: go-fmt
      - id: go-imports
      - id: go-cyclo
        args: [ -over=34 ]
      - id: golangci-lint
      - id: go-critic
      - id: go-unit-tests
      - id: go-build
      - id: go-mod-tidy